dreambuy/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views

from rest_framework import routers

app_name = "dreambuy"

urlpatterns = [
    #/dreambuy/
    url(r'^$',views.index, name='index'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login_user/$', views.login_user, name='login_user'),
    url(r'^logout_user/$', views.logout_user, name='logout_user'),
    # #/dreambuy/id/
    url(r'^(?P<prdt_id>[0-9]+)/$',views.detail, name='detail'),
    url(r'bid/(?P<prdt_id>\w+)$',views.place_bid, name='place_bid'),
    url(r'^Api_detail/$',views.Api_detail, name='Api_detail'),
    url(r'bid/view_url/',views.form_request_view, name='view_name'),
    url(r'user_bids/',views.user_bids, name='user_bids'),
    url(r'pymnt_success/',views.pymnt_success, name='pymntsuccess'),
    # url(r'pymnt/(?P<slug>[a-zA-Z0-9_.-]+)/$', views.pymnt, name='pymnt'),
    url(r'pymnt/(?P<slug>\w+)$', views.pymnt, name='pymnt'),
    url (r'FAQs/$',views.FAQs)
]

website/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from rest_framework import routers
from dreambuy import views
from rest_framework.urlpatterns import format_suffix_patterns
from api.resources import Products_list_api,UserResource
import re
from tastypie.api import Api

v1_api = Api(api_name='v1')
v1_api.register(UserResource())
v1_api.register(Products_list_api())
# v1_api.register(CreateUserResource())
# products_list_api = Products_list_api()

# router = routers.DefaultRouter()
# router.register(r'users', views.UserViewSet)
# router.register(r'groups', views.GroupViewSet)
# router.register(r'Products_listapi', views.ProductViewSet)

app_name = 'dreambuy'

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^dreambuy/', include('dreambuy.urls', namespace='dreambuy', app_name='dreambuy')),
    url(r'^', include('dreambuy.urls', namespace='dreambuy', app_name='dreambuy')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^api/', include(v1_api.urls)),
    url(r'^api_productslist/',views.get_Product_list),
    url(r'^api_reg/$',views.CreateAPIView.as_view(),name='user'),
    # url (r'^Products_listapi/$',views.ProductViewSet,name='ProductViewSet')
    url(r'pymnt/$', views.pymnt, name='pymnt'),
    url(r'^login_user/$', views.login_user, name='login_user'),
    url(r'^register/$', views.register, name='register'),
    url (r'FAQs/$',views.FAQs)
]

dreambuy/models.py
from django.db import models
from django.contrib.auth.models import Permission, User

import datetime

# Create your models here.


# class Category(models.Model):
#     category = models.CharField(max_length=250)
#
#     def __str__(self):
#         return self.category



def prdtcode():
    import datetime
    nums =[1,2,3,4,5,6,7,8,9,0]
    alphs = ['a','b','c','d','e','f','g','h','i','j']

    now = datetime.datetime.now()
    datestr = str(now.year)
    if now.month < 10:
        datestr += '0'
    datestr += str(now.month)
    if now.day < 10:
        datestr += '0'
    datestr += str(now.day)
    if now.hour < 10:
        datestr += '0'
    datestr += str(now.hour)
    if now.minute < 10:
        datestr += '0'
    datestr += str(now.minute)
    datestrc =''
    # print (datestr)
    for i in  (datestr):
        datestrc += (alphs[int(i)-1])
    return (datestrc)


class Product(models.Model):
    Product_id = models.CharField(max_length=50,unique=True,blank=False,default=prdtcode)
    user = models.ForeignKey(User, default=1)
    # Product_category = models.ForeignKey(Category, on_delete=models.CASCADE)
    Product_name = models.CharField(max_length=50,unique=True,blank=False)
    Product_brand = models.CharField(max_length=250,blank=False)
    Product_year = models.CharField(max_length=250)
    Product_price = models.IntegerField(blank=False)
    Product_image = models.CharField(max_length=25000000, default='http://www.freeiconspng.com/uploads/no-image-icon-15.png')
    Product_image1 = models.CharField(max_length=25000000, default='http://www.freeiconspng.com/uploads/no-image-icon-15.png')
    Product_image2= models.CharField(max_length=25000000, default='http://www.freeiconspng.com/uploads/no-image-icon-15.png')
    Product_image3 = models.CharField(max_length=25000000, default='http://www.freeiconspng.com/uploads/no-image-icon-15.png')
    Product_image4 = models.CharField(max_length=25000000, default='http://www.freeiconspng.com/uploads/no-image-icon-15.png')
    Product_image5 = models.CharField(max_length=25000000, default='http://www.freeiconspng.com/uploads/no-image-icon-15.png')
    Product_details = models.CharField(max_length=11250)
    Product_bids = models.IntegerField(default=0)
    Product_each_bid_cost = models.IntegerField(default=500)
    Product_MAX_bid = models.IntegerField(default=0)
    Product_bid_percent = models.IntegerField(default=0)
    #
    #
    # # def _max_bids(self):
    # #     mbids = int(self.Product_price/self.Product_each_bid_cost)
    # #     return mbids
    # # Product_max_bids = property(_max_bids)
    #
    # Product_max_bids = 10
    #
    # # def _bids_remaining(self):
    # #     bids_remaining = int(self.Product_max_bids - self.Product_bids)
    # #     return bids_remaining
    # # Product_bids_remaining = property(_bids_remaining)
    # Product_bids_remaining = 10
    # # def _bids_percent(self):
    # #     bids_percent = int(self.Product_bids/self.Product_max_bids)
    # #     return bids_percent
    # # Product_bids_percent = property(_bids_percent)
    #
    #
    # # def _max_bids(self):
    # #     if self.Product_bids_remaining > 6:
    # #         Product_MAX_bids = 6
    # #     else:
    # #         Product_MAX_bids = self.Product_bids_remaining
    # #     return Product_MAX_bids
    # #
    # # Product_MAX_bids = property(_max_bids)
    #
    # Product_MAX_bids = 10



    def __str__(self):
        return self.Product_brand + ' - ' + self.Product_name + ' - ' + str(self.Product_price)

class userbids(models.Model):
    Product_id = models.IntegerField()
    Product_name = models.CharField(max_length=250)
    user = models.ForeignKey(User, default=1)
    userid = models.IntegerField(default=1)
    bid_time = models.CharField(max_length=250)
    bid_count = models.IntegerField()
    pymnt_status = models.CharField(max_length=10, default=1)
    cur_prdt_bid_price = models.IntegerField(default=500)
    purpose = models.CharField(max_length=10, default=1)
    payment_request_id = models.CharField(max_length=10, default=1)

dreambuy/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import  Product


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']


class NameForm(forms.Form):
    your_name = forms.CharField(label='Your name', max_length=100)

dreambuy/views.py
import datetime
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404,redirect
from django.http import HttpResponse
from .models import Product, userbids
from django.http import Http404, HttpResponseRedirect
from .forms import UserForm
# Create your views here.
from django.contrib.auth.models import User, Group
from rest_framework import viewsets
from .serializers import UserSerializer, GroupSerializer
from rest_framework.generics import CreateAPIView
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from .models import Product
from .serializers import ProdctsSerializer
from django.http import Http404
from django.core import serializers
from django.contrib.auth import get_user_model
from rest_framework.permissions import IsAuthenticated, AllowAny
from .payment import mk_pymt, pymt_status

def get_Product_list(request):
    if not request.user.is_authenticated():
        return render(request, 'dreambuy/login.html')
    else:
        prodcts_list = list(Product.objects.all())
        data = serializers.serialize('json', list(prodcts_list), fields=('Product_id','Product_name'))
        # serializer = ProdctsSerializer(prodcts_list, many = True)
        return HttpResponse(data, content_type='application/json')

# def index(request):
#     if not request.user.is_authenticated():
#         return render(request, 'dreambuy/login.html')
#     else:
#         prdt = Product.objects.all()
#         context = {'prdt': prdt}
#         return render(request,"dreambuy/index.html",context)

def index(request):
    prdt = Product.objects.all().order_by('Product_bid_percent').reverse()
    updateMAX_bid()
    updaterank()
    context = {'prdt': prdt}
    return render(request, "dreambuy/index.html", context)

def FAQs(request):
    return render(request, 'dreambuy/FAQs.html',{})

# def detail(request, prdt_id):
#     if not request.user.is_authenticated():
#         return render(request, 'dreambuy/login.html')
#     else:
#         user = request.user
#         prdt = get_object_or_404(Product, Product_id = prdt_id)
#         return render(request, 'dreambuy/details.html', {'prdt': prdt, 'user': user})

def detail(request, prdt_id):
    user = request.user
    prdt = get_object_or_404(Product, Product_id = prdt_id)
    resonse = render(request, 'dreambuy/details.html', {'prdt': prdt})
    return render(request, 'dreambuy/details.html', {'prdt': prdt})

def updateMAX_bid ():
    from . import tests
    idslist = tests.select_task_by_priority()
    for prdt_id in idslist.keys():
        # print(prdt_id)
        try:
            cur_prdt = Product.objects.get(Product_id=prdt_id)
            cur_prdt.Product_MAX_bid = int(cur_prdt.Product_price/500)
            cur_prdt.save()
        except Exception as e:
            print(e)

def updaterank ():
    from . import tests
    idslist = tests.select_task_by_priority()
    for prdt_id in idslist.keys():
        print(prdt_id)
        try:
            cur_prdt = Product.objects.get(Product_id=prdt_id)
            cur_prdt.Product_bid_percent = int((cur_prdt.Product_bids / cur_prdt.Product_MAX_bid)*100)
            cur_prdt.save()
        except Exception as e:
            print(e)

def place_bid(request, prdt_id):
    if not request.user.is_authenticated():
        return render(request, 'dreambuy/login.html')
    else:
        if prdt_id:
            if request.method == "POST":
                cur_prdt = Product.objects.get(Product_id=prdt_id)
                cur_prdt_bid_price = cur_prdt.Product_each_bid_cost
                cur_bids = cur_prdt.Product_bids
                cur_palced = int(request.POST.get("quote_bids"))
                cur_bids += cur_palced
                cur_prdt.Product_bids = cur_bids
                user = request.user
                print(user.id)
                purpose = str(prdt_id) + '_' + str(cur_palced) + '_' + str(cur_prdt_bid_price)
                # userbids.objects.create(Product_name=cur_prdt.Product_name,
                #                     Product_id=prdt_id,
                #                     user=user,
                #                     bid_time=str(datetime.datetime.now()),
                #                     bid_count=cur_palced,
                #                     cur_prdt_bid_price = cur_prdt_bid_price,
                #                     pymnt_status='started',
                #                     userid = user.id,
                #                         purpose=purpose)
                cur_prdt.save()
                amt = int(cur_palced)* cur_prdt_bid_price
                purpose = str(prdt_id)+'_'+str(cur_palced)+'_'+str(cur_prdt_bid_price)
                rurl = 'http://34.230.248.248:8000/dreambuy/pymnt/'
                response = mk_pymt(amt=10, purpose=purpose, usr='test1', mblnum='', mlid='', rurl=rurl)
                # print (response)
                pymntpth = response['payment_request']['longurl']
                # print (pymntpth)
                prdt = get_object_or_404(Product, Product_id=prdt_id)
                # return render(request, 'dreambuy/details.html', {'prdt': prdt, 'user': user})
                return HttpResponseRedirect(pymntpth)
        else:
            return HttpResponse("""<h1>Error while placing your bid. Please try again.</h1><a href='dreambuy/index.html'>back</a>""")


def user_bids(request):
    if not request.user.is_authenticated():
        return render(request, 'dreambuy/login.html')
    else:
        user = request.user
        user_bids_list = userbids.objects.filter(user=user)
        context = {'user_bids_list': user_bids_list}
        return render(request,"dreambuy/profile.html",context)


def form_request_view(request, *args, **kwargs):
    if request.method == "POST":
        print(request.POST.get("quote_bids"))
        prdt = request.POST.get("Product_id")
        user = request.user
        return render(request,'dreambuy/details.html', {'prdt': prdt, 'user': user})

def Api_detail(request, prdt_id=1):
    if not request.user.is_authenticated():
        return render(request, 'dreambuy/login.html')
    else:
        prodcts_list = list(Product.objects.get(Product_id=prdt_id))
        data = serializers.serialize('json', list(prodcts_list), fields=('Product_id','Product_name'))
        return HttpResponse(data, content_type='application/json')

def register(request):
    form = UserForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user.set_password(password)
        user.save()
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return redirect('/')
    context = {
        "form": form,
    }
    return render(request, 'dreambuy/register.html', context)


def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return redirect('/')
            else:
                return render(request, 'dreambuy/login.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'dreambuy/login.html', {'error_message': 'Invalid login'})
    return render(request, 'dreambuy/login.html', )

def logout_user(request):
    logout(request)
    form = UserForm(request.POST or None)
    context = {
        "form": form,
    }
    return render(request, 'dreambuy/login.html', context)

def pymnt_success(request):
    if not request.user.is_authenticated():
        return render(request, 'dreambuy/login.html')
    else:
        user = request.user
        context = {'user': user}
        return render(request,"dreambuy/pymnt_sucess.html",context)


def pymnt(request):
    # print(request)
    if not request.user.is_authenticated():
        return render(request, 'dreambuy/login.html')
    else:
        str_request = str(request)
        strt = str_request.find("&payment_request_id=")
        payment_request_id = str_request[strt+len('&payment_request_id='):-2]
        response = pymt_status(payment_request_id)
        context = {}
        print(response)
        prdt_id =int(response[0][:1])
        print('prdt_id',prdt_id)
        cur_prdt = Product.objects.get(Product_id=prdt_id)
        cur_prdt_bid_price = cur_prdt.Product_each_bid_cost
        # cur_bids = cur_prdt.Product_bids
        cur_palced = int(response[0][2:3])
        print("cur_palced",cur_palced)
        # cur_bids += cur_palced
        # cur_prdt.Product_bids = cur_bids
        user = request.user
        print(user.id)
        purpose = str(prdt_id) + '_' + str(cur_palced) + '_' + str(cur_prdt_bid_price)
        userbids.objects.create(Product_name=cur_prdt.Product_name,
                                Product_id=prdt_id,
                                user=user,
                                bid_time=str(datetime.datetime.now()),
                                bid_count=cur_palced,
                                cur_prdt_bid_price=cur_prdt_bid_price,
                                pymnt_status='started',
                                userid=user.id,
                                purpose=purpose,
                                payment_request_id=payment_request_id)
        if response[1]!= 'Credit':
            cur_bids = cur_prdt.Product_bids
            cur_bids -= cur_palced
            cur_prdt.Product_bids = cur_bids
            cur_prdt.save()
        return render(request, "dreambuy/pymnt_sucess.html", context)

dreambuy/templates/dreambuy/base_test.html
<!DOCTYPE html>
<html lang="en">
<head>

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700" rel="stylesheet">

    <meta charset="UTF-8">
    <title>{% block title %}Dreambuy{% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'dreambuy/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>



    <style>
.button {
    background-color: #4CAF50;
    border: none;
    color: white;
    padding: 4px 10px;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    font-size: 16px;
    margin: 0px 2px;
    cursor: pointer;
}

.bid_button {
background-color: #4CAF50; color: black;
padding: 4px 10px;

}

#overlay {
     visibility: hidden;
     position: absolute;
     left: 0px;
     top: 0px;
     width:100%;
     height:100%;
     text-align:center;
     z-index: 1000;
     background-image:url(background-trans.png);
}
#overlay div {
     width:300px;
     margin: 100px auto;
     background-color: #fff;
     border:1px solid #000;
     padding:15px;
     text-align:center;
}


.wrapper {
    text-align: center;
}


</style>

</head>
<body>
<nav class="navbar navbar-inverse">
    <div class = "container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="topNavBar">
                <a href="{% url 'dreambuy:logout_user' %}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                    </a>
            </button>
            <a class="navbar-brand" href="{% url 'dreambuy:index' %}"> DreamBuy</a>
        </div>


        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class=""><a href="{% url 'dreambuy:index' %}"><span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span>&nbsp; Products</a></li>

            </ul>

            <ul class="nav navbar-nav navbar-right">

                <li>
                    <a href="{% url 'dreambuy:logout_user' %}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                    </a>
                </li>
            </ul>

        </div>
    </div>
</nav>
{% block body %}
{% endblock %}
</body>


</html>

dreambuy/templates/dreambuy/form_template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2" for="song_title">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

dreambuy/templates/dreambuy/login.html
{% extends 'dreambuy/base.html' %}
{% block login_active %}active{% endblock %}
{% block body %}

<div class = "container">
	<div class="wrapper">
		<form class="form-signin" role="form" action="{% url 'dreambuy:login_user'%}" method="post" enctype="multipart/form-data">
			{% csrf_token %}
		    <h3 class="form-signin-heading">Welcome Back! Please Sign In</h3>
			  <hr class="colorgraph"><br>

			  <input id="id_username" type="text" class="form-control" name="username" placeholder="Username" required="" autofocus="" />

			  <input id="id_password" type="password" class="form-control" name="password" placeholder="Password" required=""/>

			  <button class="btn btn-lg btn-primary btn-block"  name="submit" value="Login" type="Submit">Login</button>
		</form>
	<div class="panel-footer">
                    Don't have an account? <a href="{% url 'dreambuy:register' %}">Click here</a> to register.
 </div>

    </div>

</div>

<style>


    .wrapper {
	margin-top: 80px;
	margin-bottom: 20px;
}

.form-signin {
  max-width: 420px;
  padding: 30px 38px 66px;
  margin: 0 auto;
  background-color: #eee;
  border: 3px dotted rgba(0,0,0,0.1);
  }

.form-signin-heading {
  text-align:center;
  margin-bottom: 30px;
}

.form-control {
  position: relative;
  font-size: 16px;
  height: auto;
  padding: 10px;
}

input[type="text"] {
  margin-bottom: 0px;
  border-bottom-left-radius: 0;
  border-bottom-right-radius: 0;
}

input[type="password"] {
  margin-bottom: 20px;
  border-top-left-radius: 0;
  border-top-right-radius: 0;
}

.colorgraph {
  height: 7px;
  border-top: 0;
  background: #c4e17f;
  border-radius: 5px;
  background-image: -webkit-linear-gradient(left, #c4e17f, #c4e17f 12.5%, #f7fdca 12.5%, #f7fdca 25%, #fecf71 25%, #fecf71 37.5%, #f0776c 37.5%, #f0776c 50%, #db9dbe 50%, #db9dbe 62.5%, #c49cde 62.5%, #c49cde 75%, #669ae1 75%, #669ae1 87.5%, #62c2e4 87.5%, #62c2e4);
  background-image: -moz-linear-gradient(left, #c4e17f, #c4e17f 12.5%, #f7fdca 12.5%, #f7fdca 25%, #fecf71 25%, #fecf71 37.5%, #f0776c 37.5%, #f0776c 50%, #db9dbe 50%, #db9dbe 62.5%, #c49cde 62.5%, #c49cde 75%, #669ae1 75%, #669ae1 87.5%, #62c2e4 87.5%, #62c2e4);
  background-image: -o-linear-gradient(left, #c4e17f, #c4e17f 12.5%, #f7fdca 12.5%, #f7fdca 25%, #fecf71 25%, #fecf71 37.5%, #f0776c 37.5%, #f0776c 50%, #db9dbe 50%, #db9dbe 62.5%, #c49cde 62.5%, #c49cde 75%, #669ae1 75%, #669ae1 87.5%, #62c2e4 87.5%, #62c2e4);
  background-image: linear-gradient(to right, #c4e17f, #c4e17f 12.5%, #f7fdca 12.5%, #f7fdca 25%, #fecf71 25%, #fecf71 37.5%, #f0776c 37.5%, #f0776c 50%, #db9dbe 50%, #db9dbe 62.5%, #c49cde 62.5%, #c49cde 75%, #669ae1 75%, #669ae1 87.5%, #62c2e4 87.5%, #62c2e4);
}


</style>
{% endblock %}

dreambuy/templates/dreambuy/login_old.html
{% extends 'dreambuy/base_visitor.html' %}
{% block title %}Log In{% endblock %}
{% block login_active %}active{% endblock %}

{% block body %}



<div class = "container">
	<div class="wrapper">

            		<form class="form-signin" role="form" name="Login_Form" action="{% url 'dreambuy:login_user'%}" method="post" enctype="multipart/form-data">

		    <h3 class="form-signin-heading">Welcome Back! Please Sign In</h3>
			  <hr class="colorgraph"><br>

			  <input id="id_username" type="text" class="form-control" name="Username" placeholder="Username" required="" autofocus="" />

			  <input id="id_password" type="password" class="form-control" name="Password" placeholder="Password" required=""/>

			  <button class="btn btn-lg btn-primary btn-block"  name="Submit" value="Login" type="Submit">Login</button>
		</form>
	<div class="panel-footer">
                    Don't have an account? <a href="{% url 'dreambuy:register' %}">Click here</a> to register.
 </div>

    </div>

</div>


<style>


    .wrapper {
	margin-top: 80px;
	margin-bottom: 20px;
}

.form-signin {
  max-width: 420px;
  padding: 30px 38px 66px;
  margin: 0 auto;
  background-color: #eee;
  border: 3px dotted rgba(0,0,0,0.1);
  }

.form-signin-heading {
  text-align:center;
  margin-bottom: 30px;
}

.form-control {
  position: relative;
  font-size: 16px;
  height: auto;
  padding: 10px;
}

input[type="text"] {
  margin-bottom: 0px;
  border-bottom-left-radius: 0;
  border-bottom-right-radius: 0;
}

input[type="password"] {
  margin-bottom: 20px;
  border-top-left-radius: 0;
  border-top-right-radius: 0;
}

.colorgraph {
  height: 7px;
  border-top: 0;
  background: #c4e17f;
  border-radius: 5px;
  background-image: -webkit-linear-gradient(left, #c4e17f, #c4e17f 12.5%, #f7fdca 12.5%, #f7fdca 25%, #fecf71 25%, #fecf71 37.5%, #f0776c 37.5%, #f0776c 50%, #db9dbe 50%, #db9dbe 62.5%, #c49cde 62.5%, #c49cde 75%, #669ae1 75%, #669ae1 87.5%, #62c2e4 87.5%, #62c2e4);
  background-image: -moz-linear-gradient(left, #c4e17f, #c4e17f 12.5%, #f7fdca 12.5%, #f7fdca 25%, #fecf71 25%, #fecf71 37.5%, #f0776c 37.5%, #f0776c 50%, #db9dbe 50%, #db9dbe 62.5%, #c49cde 62.5%, #c49cde 75%, #669ae1 75%, #669ae1 87.5%, #62c2e4 87.5%, #62c2e4);
  background-image: -o-linear-gradient(left, #c4e17f, #c4e17f 12.5%, #f7fdca 12.5%, #f7fdca 25%, #fecf71 25%, #fecf71 37.5%, #f0776c 37.5%, #f0776c 50%, #db9dbe 50%, #db9dbe 62.5%, #c49cde 62.5%, #c49cde 75%, #669ae1 75%, #669ae1 87.5%, #62c2e4 87.5%, #62c2e4);
  background-image: linear-gradient(to right, #c4e17f, #c4e17f 12.5%, #f7fdca 12.5%, #f7fdca 25%, #fecf71 25%, #fecf71 37.5%, #f0776c 37.5%, #f0776c 50%, #db9dbe 50%, #db9dbe 62.5%, #c49cde 62.5%, #c49cde 75%, #669ae1 75%, #669ae1 87.5%, #62c2e4 87.5%, #62c2e4);
}


</style>
{% endblock %}

dreambuy/templates/dreambuy/pymnt_sucess.html
{% extends 'dreambuy/base.html' %}
{% block body %}
<div class="container">
	<div class="row text-center">
        <div class="col-sm-6 col-sm-offset-3">
        <br><br> <h2 style="color:#0fad00">Payment Success</h2>
        <p style="font-size:20px;color:#5C5C5C;">Thank you for placing bid. We have sent you an email with details
Please go to your email now and verify.</p>
        <a href="{% url 'dreambuy:index' %}" class="btn btn-success">     Home      </a>
    <br><br>
        </div>
	</div>
</div>
{% endblock %}

dreambuy/templates/dreambuy/register.html
{% extends 'dreambuy/base.html' %}
{% block login_active %}active{% endblock %}
{% block title %}Register{% endblock %}
{% block register_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Register for an Account</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'dreambuy/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Already have an account? <a href="{% url 'dreambuy:login_user' %}">Click here</a> to log in.
                </div>
            </div>
        </div>
    </div>

</div>








{% endblock %}